version: '3.8'

services:
  frontend:
    build:
      context: ./Techdome-frontend
    ports:
      - "3000:3000"
    networks:
      - techdome_network
    depends_on:
      - backend

  backend:
    build:
      context: ./Techdome-backend
    ports:
      - "5000:5000"
    networks:
      - techdome_network
    environment:
      - PORT=5000
      - DB=mongodb://mongo:27017/mydb  # MongoDB connection string
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"     
    networks:
      - techdome_network
    volumes:
      - mongo_data:/data/db

networks:
  techdome_network:
    driver: bridge 

volumes:
  mongo_data:
    driver: local  # Persist MongoDB data locally